-- Primer Lab V33 - YENİ BİLGİSAYAR İÇİN TAM VERİTABANI ŞEMASI
--
-- Boş bir "primerlab" veritabanında tüm tabloları oluşturur. Uygulamanın
-- kullandığı her tablo ve sütun buradadır (EF migration'ları yalnız 4 tablo
-- oluşturuyordu; diğerleri eski sürüm betiklerine dağılmıştı).
--
-- Tekrar çalıştırılabilir: var olan tablo/sütun/indeks atlanır, veri silinmez.
-- Eski bilgisayardan alınan "Tam Yedek" bu şemaya Ayarlar > Yedek Geri Yükle
-- ile geri yüklenebilir. Bu yüzden sonradan eklenen sütunlar boş bırakılabilir
-- (NULL) veya varsayılan değerlidir.

SET client_encoding = 'UTF8';
-- "zaten var, atlanıyor" bildirimleri gizlenir; gerçek uyarılar (WARNING) görünür.
SET client_min_messages = warning;

BEGIN;

-- ---------------------------------------------------------------- EF tabloları
CREATE TABLE IF NOT EXISTS "Hekimler"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AdSoyad" text NOT NULL,
    "KlinikAdi" text NULL,
    "Telefon" text NULL,
    "Email" text NULL,
    "Aktif" boolean NOT NULL DEFAULT true,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Teknisyenler"
(
    "Id" serial PRIMARY KEY,
    "AdSoyad" character varying(150) NOT NULL,
    "Aktif" boolean NOT NULL DEFAULT true,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Hastalar"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "AdSoyad" text NOT NULL,
    "HekimId" integer NOT NULL,
    "Telefon" text NULL,
    "Notlar" text NULL,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Aktif" boolean NOT NULL DEFAULT true,
    CONSTRAINT "FK_Hastalar_Hekimler_HekimId" FOREIGN KEY ("HekimId")
        REFERENCES "Hekimler"("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "Siparisler"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "HastaId" integer NOT NULL,
    "Durum" text NOT NULL,
    "Notlar" text NULL,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "TeslimTarihi" timestamp with time zone NULL,
    "Aktif" boolean NOT NULL DEFAULT true,
    CONSTRAINT "FK_Siparisler_Hastalar_HastaId" FOREIGN KEY ("HastaId")
        REFERENCES "Hastalar"("Id") ON DELETE RESTRICT
);

-- Siparisler: uygulamanın sonradan eklediği alanlar
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "ParaBirimi" character varying(10) NOT NULL DEFAULT 'TRY';
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "Silindi" boolean NULL DEFAULT false;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "SilinmeTarihi" timestamp with time zone NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "OnayDurumu" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "Kaynak" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "TerminTarihi" timestamp with time zone NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "DisRengi" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "DisSemasi" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "Materyal" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "TeknisyenId" integer NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "TamamlamaOncekiDurum" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "TamamlamaTalepTarihi" timestamp with time zone NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "TasarimIndirildi" boolean NULL DEFAULT false;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "TasarimIndirmeTarihi" timestamp with time zone NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "Oncelik" text NULL DEFAULT 'Normal';
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "UretimNotu" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "UretimAsamasi" text NULL DEFAULT 'Bekliyor';
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "KaliteKontrolDurumu" text NULL DEFAULT 'Bekliyor';
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "KaliteKontrolNotu" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "KaliteKontrolTarihi" timestamp with time zone NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "PortalTasarimKaynagi" text NULL;
ALTER TABLE "Siparisler" ADD COLUMN IF NOT EXISTS "PortalGonderimId" uuid NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Siparisler_Teknisyenler_TeknisyenId') THEN
        ALTER TABLE "Siparisler"
            ADD CONSTRAINT "FK_Siparisler_Teknisyenler_TeknisyenId"
            FOREIGN KEY ("TeknisyenId") REFERENCES "Teknisyenler"("Id") ON DELETE RESTRICT
            NOT VALID; -- mevcut eski kayıtlar kontrol edilmez; yeni kayıtlar kontrol edilir
    END IF;
EXCEPTION WHEN others THEN
    RAISE WARNING 'Teknisyen yabancı anahtarı eklenemedi: %', SQLERRM;
END $$;

CREATE TABLE IF NOT EXISTS "SiparisKalemleri"
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SiparisId" integer NOT NULL,
    "IsTuru" text NOT NULL,
    "Adet" integer NOT NULL DEFAULT 1,
    "BirimFiyat" numeric(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT "FK_SiparisKalemleri_Siparisler_SiparisId" FOREIGN KEY ("SiparisId")
        REFERENCES "Siparisler"("Id") ON DELETE CASCADE
);

-- ---------------------------------------------------------------- İş akışı
CREATE TABLE IF NOT EXISTS "SiparisDurumGecmisi"
(
    "Id" serial PRIMARY KEY,
    "SiparisId" integer NOT NULL,
    "EskiDurum" text NULL,
    "YeniDurum" text NOT NULL,
    "DegisimTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Aciklama" text NULL
);

CREATE TABLE IF NOT EXISTS "IsDosyalari"
(
    "Id" serial PRIMARY KEY,
    "SiparisId" integer NOT NULL,
    "DosyaTuru" character varying(40) NOT NULL DEFAULT 'Diger',
    "OrijinalDosyaAdi" character varying(300) NOT NULL,
    "SaklananDosyaAdi" character varying(300) NOT NULL,
    "Uzanti" character varying(20) NOT NULL DEFAULT '',
    "Boyut" bigint NOT NULL DEFAULT 0,
    "YuklemeTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "IsMesajlari"
(
    "Id" serial PRIMARY KEY,
    "SiparisId" integer NOT NULL,
    "GonderenTipi" character varying(40) NOT NULL DEFAULT 'Laboratuvar',
    "GonderenAdi" character varying(150) NULL,
    "Mesaj" text NOT NULL,
    "Tarih" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------- Muhasebe
CREATE TABLE IF NOT EXISTS "HekimFiyatlari"
(
    "Id" serial PRIMARY KEY,
    "HekimId" integer NOT NULL,          -- 0 = merkezi iş kataloğu (yabancı anahtar yok)
    "IsTuru" character varying(200) NOT NULL,
    "BirimFiyat" numeric(18,2) NOT NULL DEFAULT 0,
    "ParaBirimi" character varying(10) NOT NULL DEFAULT 'TRY',
    "Sira" integer NOT NULL DEFAULT 0,
    "Aktif" boolean NOT NULL DEFAULT true,
    CONSTRAINT "UX_HekimFiyatlari_Hekim_IsTuru" UNIQUE ("HekimId", "IsTuru")
);

CREATE TABLE IF NOT EXISTS "Tahsilatlar"
(
    "Id" serial PRIMARY KEY,
    "HekimId" integer NOT NULL REFERENCES "Hekimler"("Id") ON DELETE RESTRICT,
    "Tutar" numeric(18,2) NOT NULL,
    "ParaBirimi" character varying(10) NOT NULL DEFAULT 'TRY',
    "Tarih" timestamp with time zone NOT NULL,
    "OdemeTuru" text NULL,
    "IslemNo" character varying(150) NULL,
    "Aciklama" character varying(500) NULL,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CK_Tahsilatlar_ParaBirimi" CHECK ("ParaBirimi" IN ('TRY','EUR','USD'))
);

CREATE TABLE IF NOT EXISTS "Giderler"
(
    "Id" serial PRIMARY KEY,
    "Tarih" timestamp with time zone NOT NULL,
    "Kategori" character varying(100) NOT NULL DEFAULT 'Diğer',
    "Aciklama" character varying(500) NULL,
    "Tutar" numeric(18,2) NOT NULL,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "CariDonemleri"
(
    "Id" serial PRIMARY KEY,
    "HekimId" integer NOT NULL REFERENCES "Hekimler"("Id") ON DELETE RESTRICT,
    "BaslangicTarihi" timestamp with time zone NULL,
    "KapanisTarihi" timestamp with time zone NOT NULL,
    "IsSayisi" integer NOT NULL DEFAULT 0,
    "ToplamlarJson" text NOT NULL DEFAULT '{}',
    "TahsilatlarJson" text NOT NULL DEFAULT '{}',
    "BakiyelerJson" text NOT NULL DEFAULT '{}',
    "IslerSnapshotJson" text NOT NULL DEFAULT '[]',
    "TahsilatlarSnapshotJson" text NOT NULL DEFAULT '[]',
    "DevirEklendi" boolean NOT NULL DEFAULT true,
    "GeriAlindi" boolean NOT NULL DEFAULT false,
    "Notlar" text NULL,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "GuncellemeTarihi" timestamp with time zone NULL
);

-- ---------------------------------------------------------------- Hekim Portalı
CREATE TABLE IF NOT EXISTS "HekimPortalHesaplari"
(
    "Id" serial PRIMARY KEY,
    "HekimId" integer NOT NULL REFERENCES "Hekimler"("Id") ON DELETE CASCADE,
    "KullaniciAdi" character varying(100) NOT NULL,
    "ParolaHash" character varying(300) NOT NULL,
    "ParolaSalt" character varying(200) NOT NULL,
    "Aktif" boolean NOT NULL DEFAULT true,
    "SonGirisTarihi" timestamp with time zone NULL,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "GuncellemeTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UX_HekimPortalHesaplari_HekimId" UNIQUE ("HekimId"),
    CONSTRAINT "UX_HekimPortalHesaplari_KullaniciAdi" UNIQUE ("KullaniciAdi")
);

-- ---------------------------------------------------------------- Mail
CREATE TABLE IF NOT EXISTS "MailGelenler"
(
    "Id" serial PRIMARY KEY,
    "Tarih" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Gonderen" character varying(300) NULL,
    "Konu" character varying(500) NULL,
    "Gövde" text NULL,
    "HekimId" integer NULL REFERENCES "Hekimler"("Id") ON DELETE SET NULL,
    "HastaAdi" character varying(300) NULL,
    "IsTuru" character varying(300) NULL,
    "DisRengi" character varying(100) NULL,
    "Materyal" character varying(150) NULL,
    "Notlar" text NULL,
    "Aktarildi" boolean NOT NULL DEFAULT false,
    "MesajId" character varying(200) NULL,
    "Klinik" character varying(300) NULL,
    "UyeSayisi" integer NULL,
    "DisNo" character varying(200) NULL,
    "ReferansKodu" character varying(200) NULL,
    "Dosyalar" text NULL,
    "WetransferLinkleri" text NULL,
    "AnalizKaynagi" character varying(100) NULL,
    "Guven" double precision NULL,
    "IncelemeGerekli" boolean NOT NULL DEFAULT false,
    "SenkronTarihi" timestamp with time zone NULL
);

CREATE TABLE IF NOT EXISTS "MailDosyalari"
(
    "Id" serial PRIMARY KEY,
    "MailId" integer NOT NULL REFERENCES "MailGelenler"("Id") ON DELETE CASCADE,
    "DosyaAdi" character varying(300) NOT NULL,
    "DosyaYolu" text NOT NULL,
    "Boyut" bigint NOT NULL DEFAULT 0,
    "MimeType" character varying(200) NULL,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------- Eski sistem arşivi
CREATE TABLE IF NOT EXISTS "LegacyArsivKayitlari"
(
    "Id" serial PRIMARY KEY,
    "Tur" character varying(50) NOT NULL,
    "LegacyId" bigint NULL,
    "KayitTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "JsonData" jsonb NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS "LegacyImportBilgisi"
(
    "Id" serial PRIMARY KEY,
    "DosyaAdi" text NULL,
    "ImportTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DoktorSayisi" integer NULL DEFAULT 0,
    "TeknisyenSayisi" integer NULL DEFAULT 0,
    "IsSayisi" integer NULL DEFAULT 0,
    "BekleyenIsSayisi" integer NULL DEFAULT 0,
    "TahsilatSayisi" integer NULL DEFAULT 0,
    "GiderSayisi" integer NULL DEFAULT 0,
    "Notlar" text NULL
);

CREATE TABLE IF NOT EXISTS "LegacyImportMap"
(
    "Tur" character varying(50) NOT NULL,
    "LegacyId" bigint NOT NULL,
    "NewId" bigint NOT NULL,
    "OlusturmaTarihi" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK_LegacyImportMap" PRIMARY KEY ("Tur", "LegacyId")
);

-- ---------------------------------------------------------------- Sistem günlüğü
CREATE TABLE IF NOT EXISTS "SistemIslemGunlugu"
(
    "Id" bigserial PRIMARY KEY,
    "Tarih" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "Metot" character varying(12) NOT NULL,
    "Yol" character varying(500) NOT NULL,
    "DurumKodu" integer NOT NULL,
    "SureMs" integer NOT NULL DEFAULT 0,
    "RequestId" character varying(150) NOT NULL
);

-- ---------------------------------------------------------------- İndeksler
CREATE INDEX IF NOT EXISTS "IX_Hekimler_AdSoyad" ON "Hekimler" ("AdSoyad");
CREATE INDEX IF NOT EXISTS "IX_Hastalar_AdSoyad" ON "Hastalar" ("AdSoyad");
CREATE INDEX IF NOT EXISTS "IX_Hastalar_HekimId" ON "Hastalar" ("HekimId");
CREATE INDEX IF NOT EXISTS "IX_Siparisler_HastaId" ON "Siparisler" ("HastaId");
CREATE INDEX IF NOT EXISTS "IX_Siparisler_Durum" ON "Siparisler" ("Durum");
CREATE INDEX IF NOT EXISTS "IX_Siparisler_Silindi_Durum" ON "Siparisler" ("Silindi", "Durum");
CREATE INDEX IF NOT EXISTS "IX_Siparisler_OnayDurumu" ON "Siparisler" ("OnayDurumu");
CREATE INDEX IF NOT EXISTS "IX_Siparisler_TeknisyenId" ON "Siparisler" ("TeknisyenId");
CREATE INDEX IF NOT EXISTS "IX_Siparisler_TerminTarihi" ON "Siparisler" ("TerminTarihi");
CREATE INDEX IF NOT EXISTS "IX_Siparisler_PortalGonderimId" ON "Siparisler" ("PortalGonderimId") WHERE "PortalGonderimId" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "IX_SiparisKalemleri_SiparisId" ON "SiparisKalemleri" ("SiparisId");
CREATE INDEX IF NOT EXISTS "IX_SiparisDurumGecmisi_Siparis_Tarih" ON "SiparisDurumGecmisi" ("SiparisId", "DegisimTarihi" DESC);
CREATE INDEX IF NOT EXISTS "IX_IsDosyalari_Siparis_Tarih" ON "IsDosyalari" ("SiparisId", "YuklemeTarihi" DESC);
CREATE INDEX IF NOT EXISTS "IX_IsMesajlari_Siparis_Tarih" ON "IsMesajlari" ("SiparisId", "Tarih");
CREATE INDEX IF NOT EXISTS "IX_Tahsilatlar_Hekim_Tarih" ON "Tahsilatlar" ("HekimId", "Tarih" DESC);
CREATE INDEX IF NOT EXISTS "IX_Giderler_Tarih" ON "Giderler" ("Tarih" DESC);
CREATE INDEX IF NOT EXISTS "IX_CariDonemleri_Hekim_Kapanis" ON "CariDonemleri" ("HekimId", "KapanisTarihi" DESC);
CREATE INDEX IF NOT EXISTS "IX_CariDonemleri_Aktif" ON "CariDonemleri" ("HekimId", "GeriAlindi", "KapanisTarihi" DESC);
CREATE INDEX IF NOT EXISTS "IX_HekimPortalHesaplari_Aktif" ON "HekimPortalHesaplari" ("Aktif", "KullaniciAdi");
-- Tekil indeksler: mevcut bir veritabanında çakışan eski kayıt varsa kurulum
-- bozulmaz, yalnız uyarı verilir.
DO $$
BEGIN
    CREATE UNIQUE INDEX IF NOT EXISTS "UX_HekimPortalHesaplari_KullaniciAdi_Lower" ON "HekimPortalHesaplari" (LOWER("KullaniciAdi"));
EXCEPTION WHEN others THEN
    RAISE WARNING 'Portal kullanıcı adı indeksi eklenemedi: %', SQLERRM;
END $$;
DO $$
BEGIN
    CREATE UNIQUE INDEX IF NOT EXISTS "UX_MailGelenler_MesajId" ON "MailGelenler" ("MesajId") WHERE "MesajId" IS NOT NULL;
EXCEPTION WHEN others THEN
    RAISE WARNING 'Mail mesaj indeksi eklenemedi: %', SQLERRM;
END $$;
CREATE INDEX IF NOT EXISTS "IX_MailGelenler_Tarih" ON "MailGelenler" ("Tarih" DESC);
CREATE INDEX IF NOT EXISTS "IX_MailGelenler_Inceleme" ON "MailGelenler" ("IncelemeGerekli", "Aktarildi");
CREATE INDEX IF NOT EXISTS "IX_MailDosyalari_MailId" ON "MailDosyalari" ("MailId");
CREATE INDEX IF NOT EXISTS "IX_LegacyArsiv_Tur_Tarih" ON "LegacyArsivKayitlari" ("Tur", "KayitTarihi" DESC);
CREATE INDEX IF NOT EXISTS "IX_LegacyImportMap_NewId" ON "LegacyImportMap" ("NewId");
CREATE INDEX IF NOT EXISTS "IX_SistemIslemGunlugu_Tarih" ON "SistemIslemGunlugu" ("Tarih" DESC);

-- EF migration geçmişi (uygulama migration çalıştırmaz; kayıt tutarlılık içindir)
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory"
(
    "MigrationId" character varying(150) NOT NULL PRIMARY KEY,
    "ProductVersion" character varying(32) NOT NULL
);
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES
    ('20260912202250_InitialCreate', '10.0.12'),
    ('20260912212026_AddHastaSiparisYapisi', '10.0.12')
ON CONFLICT ("MigrationId") DO NOTHING;

-- ---------------------------------------------------------------- Uygulama rolü yetkileri
-- primerlab_app rolü kurulum betiği tarafından oluşturulur. Rol süper kullanıcı
-- değildir; yalnız veri işlemleri yapabilir.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'primerlab_app') THEN
        GRANT USAGE ON SCHEMA public TO primerlab_app;
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO primerlab_app;
        GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO primerlab_app;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO primerlab_app;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO primerlab_app;
    END IF;
END $$;

COMMIT;
