// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrimerLabV2.Data;

#nullable disable

namespace PrimerLabV2.Migrations
{
    [DbContext(typeof(PrimerLabDbContext))]
    partial class PrimerLabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrimerLabV2.Models.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<int>("HekimId")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdSoyad");

                    b.HasIndex("HekimId");

                    b.ToTable("Hastalar");
                });

            modelBuilder.Entity("PrimerLabV2.Models.Hekim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("KlinikAdi")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdSoyad");

                    b.ToTable("Hekimler");
                });

            modelBuilder.Entity("PrimerLabV2.Models.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HastaId")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .HasColumnType("text");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("HastaId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("PrimerLabV2.Models.SiparisKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("integer");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("IsTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiparisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.ToTable("SiparisKalemleri");
                });

            modelBuilder.Entity("PrimerLabV2.Models.Hasta", b =>
                {
                    b.HasOne("PrimerLabV2.Models.Hekim", "Hekim")
                        .WithMany("Hastalar")
                        .HasForeignKey("HekimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hekim");
                });

            modelBuilder.Entity("PrimerLabV2.Models.Siparis", b =>
                {
                    b.HasOne("PrimerLabV2.Models.Hasta", "Hasta")
                        .WithMany("Siparisler")
                        .HasForeignKey("HastaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hasta");
                });

            modelBuilder.Entity("PrimerLabV2.Models.SiparisKalemi", b =>
                {
                    b.HasOne("PrimerLabV2.Models.Siparis", "Siparis")
                        .WithMany("Kalemler")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("PrimerLabV2.Models.Hasta", b =>
                {
                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("PrimerLabV2.Models.Hekim", b =>
                {
                    b.Navigation("Hastalar");
                });

            modelBuilder.Entity("PrimerLabV2.Models.Siparis", b =>
                {
                    b.Navigation("Kalemler");
                });
#pragma warning restore 612, 618
        }
    }
}
